language: elixir
elixir:
  - 1.5.0
otp_release:
  - 20.0
env:
  - MIX_ENV=test
script:
  - "mix deps.get"
  - "mix test --trace"
  - "mix coveralls.travis"
  - "mix credo"
  - "mix dogma"
  - "mix dialyzer --unmatched_returns --error_handling --race_conditions --underspecs"
